### ISSUE TITLE
vvtool fail to render

### ISSUE THREAD

**Issue by zzttzz** [GDAOSU/vis2mesh#2]
python inference.py example/example1.ply --cam cam0
#Available Toolset#
vvtool: vvtool
o3d_vvcreator.py: o3d_vvcreator.py
ReconstructMesh: ReconstructMesh
#Project Settings#
Input Cloud: /workspace/example/example1.ply Exists: True
Input Mesh:  Exists: False
Input Textured Mesh:  Exists: False
Input Textured Mesh:  Exists: False
Base Cam:  Exists: False
Input Cam: /workspace/example/example1.ply_WORK/cam0.json Exists: True
Work Folder: /workspace/example/example1.ply_WORK Exists: True
Cam: cam0    ToolChain: NET.POINT_DELAY
ToolChain Work Folder: /workspace/example/example1.ply_WORK/VDVNet_cam0 Exists:True
Output Folder: /workspace/example/example1.ply_WORK/VDVNet_cam0/out Exists:True
-- CamCreator Cmd:
o3d_vvcreator.py --output_list=/workspace/example/example1.ply_WORK/cam0.json --width=512 --height=512 /workspace/example/example1.ply
INFO:root:Valid Cams:104
vvtool: /opt/conda/lib/libtiff.so.5: no version information available (required by /usr/lib/x86_64-linux-gnu/libopencv_imgcodecs.so.3.2)
vvtool: /opt/conda/lib/libtiff.so.5: no version information available (required by /usr/lib/x86_64-linux-gnu/libvtkIOImage-6.3.so.6.3)
vvtool: /opt/conda/lib/libtiff.so.5: no version information available (required by /usr/lib/libgdal.so.20)
vvtool: /opt/conda/lib/libtiff.so.5: no version information available (required by /usr/lib/x86_64-linux-gnu/libpoppler.so.73)
vvtool: /opt/conda/lib/libtiff.so.5: no version information available (required by /usr/lib/x86_64-linux-gnu/libgeotiff.so.2)
  0%|                                                                             | 0/104 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "tools/lib/network_predict.py", line 108, in <module>
    call_plugin(blockJson)
  File "tools/lib/network_predict.py", line 84, in call_plugin
    rawdep = readFlt(input_depth)
  File "/workspace/utils/dataset_util.py", line 8, in readFlt
    with open(path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/example/example1.ply_WORK/VDVNet_cam0/render/pt0.flt'
vvtool: /opt/conda/lib/libtiff.so.5: no version information available (required by /usr/lib/x86_64-linux-gnu/libopencv_imgcodecs.so.3.2)
vvtool: /opt/conda/lib/libtiff.so.5: no version information available (required by /usr/lib/x86_64-linux-gnu/libvtkIOImage-6.3.so.6.3)
vvtool: /opt/conda/lib/libtiff.so.5: no version information available (required by /usr/lib/libgdal.so.20)
vvtool: /opt/conda/lib/libtiff.so.5: no version information available (required by /usr/lib/x86_64-linux-gnu/libpoppler.so.73)
vvtool: /opt/conda/lib/libtiff.so.5: no version information available (required by /usr/lib/x86_64-linux-gnu/libgeotiff.so.2)
[CLOUD_BUNDLE] /workspace/example/example1.ply_WORK/VDVNet_cam0/render/pt0.uint not exists.
Traceback (most recent call last):
  File "inference.py", line 382, in <module>
    main()
  File "inference.py", line 377, in main
    config=RunProcess(config)
  File "inference.py", line 319, in RunProcess
    p = subprocess.Popen(cmdArr, stdout=subprocess.PIPE)
  File "/opt/conda/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/opt/conda/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ReconstructMesh': 'ReconstructMesh'

And I Found that vvtool is to blame:
vvtool /workspace/example/example1.ply_WORK/VDVNet_cam0/render_seg.json
vvtool: /opt/conda/lib/libtiff.so.5: no version information available (required by /usr/lib/x86_64-linux-gnu/libopencv_imgcodecs.so.3.2)
vvtool: /opt/conda/lib/libtiff.so.5: no version information available (required by /usr/lib/x86_64-linux-gnu/libvtkIOImage-6.3.so.6.3)
vvtool: /opt/conda/lib/libtiff.so.5: no version information available (required by /usr/lib/libgdal.so.20)
vvtool: /opt/conda/lib/libtiff.so.5: no version information available (required by /usr/lib/x86_64-linux-gnu/libpoppler.so.73)
vvtool: /opt/conda/lib/libtiff.so.5: no version information available (required by /usr/lib/x86_64-linux-gnu/libgeotiff.so.2)
[2021-10-11 09:26:57.946] [info] Register Plugin: DEFENV success.
[2021-10-11 09:26:57.946] [info] Register Plugin: DEFCONTEXT success.
[2021-10-11 09:26:57.946] [info] Register Plugin: PRINT success.
[2021-10-11 09:26:57.946] [info] Register Plugin: GLOB success.
[2021-10-11 09:26:57.946] [info] Register Plugin: REGEX_REPLACE success.
[2021-10-11 09:26:57.946] [info] Register Plugin: GLRENDER success.
[2021-10-11 09:26:57.946] [info] Register Plugin: GTFILTER success.
[2021-10-11 09:26:57.946] [info] Register Plugin: RAYGTFILTER success.
[2021-10-11 09:26:57.946] [info] Register Plugin: CLOUD_BUNDLE success.
[2021-10-11 09:26:57.946] [info] Register Plugin: NETWORKVISIBILITY success.
[2021-10-11 09:26:57.946] [info] Plugins registered: 10 successed 0 failed
[2021-10-11 09:26:57.946] [info] Input Json: /workspace/example/example1.ply_WORK/VDVNet_cam0/render_seg.json
[2021-10-11 09:26:57.946] [info] === Initializing Plugins ===
[2021-10-11 09:26:57.946] [info] === Input Process Units(1) ===
[2021-10-11 09:26:57.946] [info] === Processing 1/1 ===
Load Cam Info:
Peek First Cam:
------------
K: 150   0 128
  0 150 128
  0   0   1
R:   0.998805  0.0209822  -0.044135
-0.0162957  -0.708441  -0.705582
-0.0460717   0.705458  -0.707253
C:  -2.0875 -32.9513 -7.10067
w 256 h 256
Load cloud (+v 1999961)
Load mesh (+v 0) (+f 0)
Segmentation fault (core dumped)

**Comment by zzttzz** [comment]
The reason is that x11 fail to activate, thus adding _--net=host_ to _docker run -it_ solved the problem

**Comment by sxsong1207** [comment]
@zzttzz Thanks for your report! I will update the readme.
